stages:
  - compile-and-test
  - qa-report
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# -------------------------------------------------
# 1️⃣ Compile and Test
# -------------------------------------------------
compile-and-test:
  stage: compile-and-test
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn clean test
  artifacts:
    when: always
    paths:
      - allure-results/
  cache:
    paths:
      - .m2/repository

# -------------------------------------------------
# 2️⃣ QA Report (Generate Allure with Date-Time)
# -------------------------------------------------
qa-report:
  stage: qa-report
  image: frankescobar/allure-docker-service
  dependencies:
    - compile-and-test
  script:
    # Create timestamp (date + hour + min + sec)
    - TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")

    # Define report path
    - REPORT_PATH=.public/allure/${CI_COMMIT_REF_NAME}/${TIMESTAMP}

    # Create directory
    - mkdir -p $REPORT_PATH

    # Generate Allure HTML report
    - allure generate allure-results --clean -o $REPORT_PATH/allure-report

    # Print report URL clearly in logs
    - echo "=============================================="
    - echo "ALLURE REPORT URL:"
    - echo "$CI_PAGES_URL/allure/${CI_COMMIT_REF_NAME}/${TIMESTAMP}/allure-report"
    - echo "=============================================="

  artifacts:
    when: always
    paths:
      - .public/

# -------------------------------------------------
# 3️⃣ Deploy to GitLab Pages
# -------------------------------------------------
pages:
  stage: deploy
  script:
    - echo "Deploying Allure reports to GitLab Pages"
  artifacts:
    paths:
      - .public
  only:
    - main
    - develop
    - feature/*
